# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [10]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
import io
from google.colab import files
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [68]:
# In google colab, use `files.upload()` to upload the applicants_data.csv file.
uploaded = files.upload()

Saving applicants_data.csv to applicants_data (3).csv

In [69]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame

applicant_data_df = pd.read_csv(io.BytesIO(uploaded['applicants_data.csv']))

In [70]:
# View the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame

# applicant_data_df = pd.read_csv(Path("Resources/applicants_data.csv"))

# Review the DataFrame
# applicant_data_df.head()

In [13]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [14]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['EIN', 'NAME'])

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [15]:
# Create a list of categorical variables 
categorical_variables = applicant_data_df.select_dtypes(include=['object', 'category']).columns.tolist()

# Display the categorical variables list
display(categorical_variables)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [16]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse_output=False)

In [17]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [18]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data, 
    columns = enc.get_feature_names_out(categorical_variables)
)

# Review the DataFrame
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [19]:
# Create a DataFrame with only the. umerical variables
numerical_df = applicant_data_df.drop(columns = categorical_variables)

# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
applicant_df = pd.concat([encoded_df, numerical_df], axis=1)

# Review the Dataframe
applicant_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [20]:
# Define the target set y using the IS_SUCCESSFUL column
y = applicant_df['IS_SUCCESSFUL']

# Display a sample of y
y[:10]

0    1
1    1
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    0
Name: IS_SUCCESSFUL, dtype: int64

In [21]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = applicant_df.drop(columns=['IS_SUCCESSFUL'])

# Review the features DataFrame
X.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590

### Step 6: Split the features and target sets into training and testing datasets.

In [22]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [23]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [24]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [25]:
# Define the number of neurons in the output layer
number_output_neurons = 4

In [26]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + number_output_neurons) // 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

60

In [27]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + number_output_neurons) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

32

In [28]:
# Create the Sequential model instance
nn = Sequential()

In [29]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

In [30]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation='relu'))

In [31]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation='sigmoid'))

In [32]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 60)                7020

 dense_1 (Dense)             (None, 32)                1952

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 9,005
Trainable params: 9,005
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [33]:
# Compile the Sequential model
# nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [38]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5259 - accuracy: 0.7428
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5257 - accuracy: 0.7434
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5252 - accuracy: 0.7442
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5256 - accuracy: 0.7439
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5254 - accuracy: 0.7433
Epoch 6/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5257 - accuracy: 0.7438
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5255 - accuracy: 0.7441
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5256 - accuracy: 0.7434
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5257 - accuracy: 0.7439
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5252 - accuracy: 0.7433
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5256 - accuracy: 0.7440
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5254 - accuracy: 0.7435
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5252 - accuracy: 0.7435
Epoch 14/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5254 - accuracy: 0.7437
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7441
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7439
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5261 - accuracy: 0.7442
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5254 - accuracy: 0.7439
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7438
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5254 - accuracy: 0.7434
Epoch 21/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5257 - accuracy: 0.7438
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7431
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7438
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5250 - accuracy: 0.7439
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7442
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5255 - accuracy: 0.7429
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5256 - accuracy: 0.7438
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5250 - accuracy: 0.7441
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5249 - accuracy: 0.7446
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7433
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7437
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5252 - accuracy: 0.7437
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7453
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7438
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7434
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5251 - accuracy: 0.7439
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7439
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7438
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7444
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7437
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5252 - accuracy: 0.7433
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5256 - accuracy: 0.7441
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5249 - accuracy: 0.7432
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7435
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7432
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5252 - accuracy: 0.7441
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5259 - accuracy: 0.7441
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5247 - accuracy: 0.7433
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5253 - accuracy: 0.7442
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7442

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [39]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5756 - accuracy: 0.7286 - 752ms/epoch - 3ms/step
Loss: 0.5756399631500244, Accuracy: 0.7286297082901001

**bold text**### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [40]:
# Set the model's file path
file_path = "AlphabetSoup.h5"

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [41]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [42]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [43]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = hidden_nodes_layer1 + 20

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

80

In [44]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [45]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim= number_input_features, activation='relu'))


# Output layer
nn_A1.add(Dense(units=1, activation='sigmoid'))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                9360

 dense_4 (Dense)             (None, 1)                 81

=================================================================
Total params: 9,441
Trainable params: 9,441
Non-trainable params: 0
_________________________________________________________________

In [47]:
# Compile the Sequential model
nn_A1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [48]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs= 50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5831 - accuracy: 0.7182
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5575 - accuracy: 0.7280
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5536 - accuracy: 0.7284
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5529 - accuracy: 0.7296
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7304
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5497 - accuracy: 0.7314
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7320
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7311
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7333
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7321
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7327
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7332
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7320
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7334
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7334
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7334
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7333
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7348
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7337
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7341
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7346
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7355
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7352
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7372
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7363
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7351
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7353
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7346
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7352
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7360
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7361
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7362
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7353
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7355
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7363
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7362
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7364
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7367
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7358
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7356
Epoch 41/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5378 - accuracy: 0.7361
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7364
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7376
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7373
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7373
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7377
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7365
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7367
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7363
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7376

#### Alternative Model 2

In [49]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [53]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 4

In [54]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features + number_output_neurons_A2) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

60

In [55]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [57]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation='relu'))

# Output layer
nn_A2.add(Dense(units= 1, activation = 'sigmoid'))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 60)                7020

 dense_6 (Dense)             (None, 1)                 61

=================================================================
Total params: 7,081
Trainable params: 7,081
Non-trainable params: 0
_________________________________________________________________

In [58]:
# Compile the model
nn_A2.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [59]:
# Fit the model
fit_model = nn_A2.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5991 - accuracy: 0.7178
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7282
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5529 - accuracy: 0.7292
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7315
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7312
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7310
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7317
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5475 - accuracy: 0.7325
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7320
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7315
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7326
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7334
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7324
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7327
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7336
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7331
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7343
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7339
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7350
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7345
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7344
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7345
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7355
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7351
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7343
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7340
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7353
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7349
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7348
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7339
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7352
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7355
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7368
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7358
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7359
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7356
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7360
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7359
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7365
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7365
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7373
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7357
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7372
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7361
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7363
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7376
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7367
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7372
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7364
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7375

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [60]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose = 2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 1s - loss: 0.5756 - accuracy: 0.7286 - 505ms/epoch - 2ms/step
Loss: 0.5756399631500244, Accuracy: 0.7286297082901001

In [61]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose = 2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 0.5686 - accuracy: 0.7306 - 504ms/epoch - 2ms/step
Loss: 0.5685898661613464, Accuracy: 0.7306122183799744

In [62]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose = 2)
# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 1s - loss: 0.5572 - accuracy: 0.7303 - 664ms/epoch - 2ms/step
Loss: 0.5571563839912415, Accuracy: 0.7302623987197876

### Step 3: Save each of your alternative models as an HDF5 file.

In [63]:
# Set the file path for the first alternative model
file_path = 'AlphabetSoup_A1.h5'
# Export your model to a HDF5 file
nn.save(file_path)

In [65]:
# Set the file path for the second alternative model
file_path = 'AlphabetSoup_A2.h5'

# Export your model to a HDF5 file
nn.save(file_path)